version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    networks:
      - default
      - traefik_lan
    environment:
#      - PUID=1000
#      - PGID=1000
      - TZ={Timezone}
#      - PASSWORD=password #optional
#      - HASHED_PASSWORD= #optional
#      - SUDO_PASSWORD=password #optional
#      - SUDO_PASSWORD_HASH= #optional
#      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - "${CODESERVER_VOLUME}/codeserver/config:/config"
      - "${CODESERVER_VOLUME}:/data"
    ports:
      - "${CODESERVER_PORT}:8443"
    restart: unless-stopped

networks:
  traefik_lan:
    external: true
