version: "3.6"

services:
  go-photo-sync:
    container_name: go-photo-sync
    image: "ryosagisu/go-photo-sync:latest"
    user: "${PHOTOSYNC_PUID}:${DOCKER_GUID}"
    volumes:
      - ${GO_PHOTO_SYNC_VOLUME}/configs:/configs
      - ${PHOTO_VOLUME}/google-photo:/google-photo
    environment:
      - CONFIG_PATH=/configs
