version: "3.7"

services:
  jellyfin:
    container_name: jellyfin
    image: cr.hotio.dev/hotio/jellyfin
    restart: always
    ports:
      - "${JELLYFIN_PORT}:8096"
    environment:
      - PUID=${JELLYFIN_PUID}
      - PGID=${JELLYFIN_PGID}
      - UMASK=002
      - TZ=Asia/Jakarta
    volumes:
      - ${JELLYFIN_VOLUME}/config:/config
      - ${MEDIA_VOLUME}:/media
    devices:
      - "/dev/dri:/dev/dri"
