version: "3.7"
services:
  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent:latest
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - PUID=${QBITTORRENT_PUID}
      - PGID=${DOCKER_PGID}
      - UMASK=002
      - TZ=Asia/Jakarta
    volumes:
      - ${QBITTORRENT_VOLUME}/config:/config
      - ${DATA_VOLUME}/torrents:/data/torrents

  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - PUID=${RADARR_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=Asia/Jakarta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${RADARR_VOLUME}/config:/config
      - ${DATA_VOLUME}:/data

  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - PUID=${SONARR_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=Asia/Jakarta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SONARR_VOLUME}/config:/config
      - ${DATA_VOLUME}:/data

  prowlarr:
    container_name: prowlarr
    image: cr.hotio.dev/hotio/prowlarr:testing
    network_mode: "container:gluetun"
    environment:
      - PUID=${PROWLARR_PUID}
      - PGID=${DOCKER_PGID}
      - UMASK=002
      - TZ=Asia/Jakarta
    volumes:
      - ${PROWLARR_VOLUME}/config:/config

  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr:latest
    network_mode: "container:gluetun"
    restart: unless-stopped
    environment:
      - PUID=${BAZARR_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=Asia/Jakarta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BAZARR_VOLUME}/config:/config
      - ${DATA_VOLUME}/media:/data/media

  nzbget:
    container_name: nzbget
    image: cr.hotio.dev/hotio/nzbget:latest
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - PUID=${NZBGET_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=Asia/Jakarta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${NZBGET_VOLUME}/config:/config
      - ${DATA_VOLUME}/usenet:/data/usenet
