version: "3.7"
services:
  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent:latest
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - PUID=${QBITTORRENT_PUID}
      - PGID=${DOCKER_PGID}
      - UMASK=002
      - TZ=Asia/Jakarta
    volumes:
      - ${QBITTORRENT_VOLUME}/config:/config
      - ${DATA_VOLUME}/torrents:/data/torrents
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -o /dev/null -s -w \"%{http_code}\" --retry 2 --retry-delay 5 --retry-max-time 30 \"https://1.1.1.1\" || kill -s 15 -1 && (sleep 10; kill -s 9 -1)"]
    #   interval: 2m
    #   timeout: 1m
    #   start_period: 30s

  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - PUID=${RADARR_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=Asia/Jakarta
      - TP_HOTIO=true
      - TP_THEME=organizr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${RADARR_VOLUME}/config:/config
      - ${DATA_VOLUME}:/data
      - ${RADARR_VOLUME}/etc/cont-init.d/98-themepark-radarr:/etc/cont-init.d/99-themepark

  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - PUID=${SONARR_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=Asia/Jakarta
      - TP_HOTIO=true
      - TP_THEME=organizr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SONARR_VOLUME}/config:/config
      - ${DATA_VOLUME}:/data
      - ${SONARR_VOLUME}/etc/cont-init.d/98-themepark-sonarr:/etc/cont-init.d/99-themepark

  prowlarr:
    container_name: prowlarr
    image: cr.hotio.dev/hotio/prowlarr:testing
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - PUID=${PROWLARR_PUID}
      - PGID=${DOCKER_PGID}
      - UMASK=002
      - TZ=Asia/Jakarta
    volumes:
      - ${PROWLARR_VOLUME}/config:/config

  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr:latest
    network_mode: "container:gluetun"
    restart: unless-stopped
    environment:
      - PUID=${BAZARR_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=Asia/Jakarta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BAZARR_VOLUME}/config:/config
      - ${DATA_VOLUME}/media:/data/media

  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:latest
    network_mode: "container:gluetun"
    init: true
    user: ${RECYCLARR_PUID}:${DOCKER_PGID}
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ${RECYCLARR_VOLUME}/config:/config
