version: "3.7"
services:
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - PUID=${RADARR_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=Asia/Jakarta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${RADARR_VOLUME}/config:/config
      - ${DATA_VOLUME}:/data

  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - PUID=${SONARR_PUID}
      - PGID=${DOCKER_PGID}
      - TZ=Asia/Jakarta
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SONARR_VOLUME}/config:/config
      - ${DATA_VOLUME}:/data

  prowlarr:
    container_name: prowlarr
    image: cr.hotio.dev/hotio/prowlarr:testing
    network_mode: "container:gluetun"
    environment:
      - PUID=${PROWLARR_PUID}
      - PGID=${DOCKER_PGID}
      - UMASK=002
      - TZ=Asia/Jakarta
    volumes:
      - ${PROWLARR_VOLUME}/config:/config
