version: "3.8"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    restart: always
    user: "${GRAFANA_PUID}"
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - PUID=${GRAFANA_PUID}
      - PGID=${DOCKER_PGID}
    volumes:
      - ${GRAFANA_VOLUME}:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    user: "${PROMETHEUS_PUID}"
    ports:
      - "${PROMETHEUS_PORT}:9090"
    environment:
      - PUID=${PROMETHEUS_PUID}
      - PGID=${DOCKER_PGID}
    volumes:
      - ${PROMETHEUS_VOLUME}/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_VOLUME}/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   restart: always
  #   ports:
  #     - "${NODE_EXPORTER_PORT}:9100"
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  snmp-exporter:
    container_name: monitoring-snmp
    image: prom/snmp-exporter:latest
    volumes:
      - ${PROMETHEUS_VOLUME}/snmp-exporter:/etc/snmp_exporter
    restart: always
    command: --config.file=/etc/snmp_exporter/snmp.yml
