version: "3.7"

services:
  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent:latest
   environment:
      - PUID=${QBITTORRENT_PUID}
      - PGID=${QBITTORRENT_PGID}
      - UMASK=002
      - TZ=Asia/Jakarta
    volumes:
      - ${QBITTORRENT_VOLUME}/config:/config
      - ${TORRENT_VOLUME}:/torrents
