version: "3.8"
services:
  archisteamfarm:
    image: justarchi/archisteamfarm:latest
    container_name: archisteamfarm
    restart: always
    user: "${ARCHISTEAMFARM_PUID}:${ARCHISTEAMFARM_GUID}"
    networks:
      - default
      - traefik_lan
    volumes:
      - "${ARCHISTEAMFARM_VOLUME}/config:/app/config"

networks:
  traefik_lan:
    external: true
