version: "3"
services:
  archisteamfarm:
    image: justarchi/archisteamfarm:latest
    container_name: archisteamfarm
    restart: always
    user: "${ARCHISTEAMFARM_PUID}:${ARCHISTEAMFARM_GUID}"
    ports:
      - "${ARCHISTEAMFARM_PORT}:1242"
    volumes:
      - "${ARCHISTEAMFARM_VOLUME}/config:/app/config"
