version: "3"
services:
  archisteamfarm:
    image: justarchi/archisteamfarm:latest
    container_name: archisteamfarm
    restart: always
    user: "${ARCHISTEAMFARM_PUID}:${ARCHISTEAMFARM_GUID}"
    volumes:
      - "${ARCHISTEAMFARM_VOLUME}/config:/app/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.archisteamfarm.rule=Host(`archisteamfarm.${ARCHISTEAMFARM_DOMAIN}`)"
      - "traefik.http.services.archisteamfarm.loadbalancer.server.port=1242"
