version: "3.7"
services:
  dns:
    container_name: dns
    image: qmcgaw/dns
    restart: always
    networks:
      priv_lan:
        ipv4_address: ${DNS_IP}
    environment:
      - PROVIDERS=cloudflare,google,quad9
      - BLOCK_MALICIOUS=off

networks:
  priv_lan:
    external: true
