version: "3.5"

services:
  # https://github.com/mcuadros/ofelia
  # Ofelia is a modern and low footprint job scheduler for docker environments, built on Go. 
  # Ofelia aims to be a replacement for the old fashioned cron.
  ofelia:
    container_name: ofelia
    restart: unless-stopped
    image: mcuadros/ofelia:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${OFELIA_VOLUME}/config.ini:/etc/ofelia/config.ini"
