version: "3.5"

services:
  # Ofelia Job Runner (recommended for running background jobs)
  # see https://github.com/mcuadros/ofelia
  ofelia:
    container_name: ofelia
    restart: unless-stopped
    image: mcuadros/ofelia:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${OFELIA_VOLUME}/config.ini:/etc/ofelia/config.ini"
