version: "3.8"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    restart: always
    user: "${GRAFANA_PUID}"
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - PUID=${GRAFANA_PUID}
      - PGID=${DOCKER_PGID}
    volumes:
      - ${GRAFANA_VOLUME}:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    user: "${PROMETHEUS_PUID}"
    ports:
      - "${PROMETHEUS_PORT}:9090"
    environment:
      - PUID=${PROMETHEUS_PUID}
      - PGID=${DOCKER_PGID}
    volumes:
      - ${PROMETHEUS_VOLUME}/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_VOLUME}/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  snmp-exporter:
    container_name: monitoring-snmp
    image: prom/snmp-exporter:latest
    volumes:
      - ${PROMETHEUS_VOLUME}/snmp-exporter:/etc/snmp_exporter
    restart: unless-stopped
    network_mode: "service:prometheus"
    command: --config.file=/etc/snmp_exporter/snmp.yml
