version: "3.6"

services:
  homeassistant:
    container_name: "homeassistant"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${HOMEASSISTANT_VOLUME}/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  room-assistant:
    container_name: "roomassistant"
    image: "mkerix/room-assistant:latest"
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
