version: "3.6"

services:
  eclipse-mosquitto:
    container_name: "mosquitto"
    image: "eclipse-mosquitto:latest"
    restart: always
    network_mode: host
    volumes:
      - "${HOMEASSISTANT_VOLUME}/mosquitto/config:/mosquitto/config"

  node-red:
    container_name: "nodered"
    image: nodered/node-red:latest
    restart: always
    network_mode: host
    volumes:
      - "${HOMEASSISTANT_VOLUME}/nodered/config:/config"
      - "${HOMEASSISTANT_VOLUME}/nodered/data:/data"
      - "${HOMEASSISTANT_VOLUME}/nodered/ssh:/usr/src/node-red/.ssh"
    environment:
      - TZ=${TIMEZONE}

  homeassistant:
    container_name: "homeassistant"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: always
    privileged: true
    network_mode: host
    depends_on:
      - eclipse-mosquitto
      - node-red
    volumes:
      - "${HOMEASSISTANT_VOLUME}/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
