version: "3.6"

services:
  homeassistant:
    container_name: homeassistant
    restart: always
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${HOMEASSISTANT_VOLUME}/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    networks:
      priv_lan:
        ipv4_address: ${HOMEASSISTANT_IP}

networks:
  priv_lan:
    external: true
