version: "3.6"

services:
  homeassistant:
    container_name: "homeassistant"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - "${HOMEASSISTANT_VOLUME}/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    privileged: true
    network_mode: host

  room-assistant:
    container_name: "roomassistant"
    image: "mkerix/room-assistant:latest"
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - "${HOMEASSISTANT_VOLUME}/roomassistant/config:/room-assistant/config"
      - "/var/run/dbus:/var/run/dbus"

  eclipse-mosquitto:
    container_name: "homeassistant-mosquitto"
    image: "eclipse-mosquitto:latest"
    network_mode: host
    volumes:
      - "${HOMEASSISTANT_VOLUME}/mosquitto/config:/mosquitto/config"

  node-red:
    image: nodered/node-red:latest
    network_mode: host
    volumes:
      - "${HOMEASSISTANT_VOLUME}/node-red/config:/config"
    environment:
      - TZ=${TIMEZONE}
