version: "3.6"

services:
  pihole:
    container_name: pihole
    restart: always
    image: pihole/pihole:latest
    environment:
      - "TZ=${TIMEZONE}"
      - "DNS1=${CLOUDFLARED_IP}#53"
    volumes:
      - "${PIHOLE_VOLUME}/etc/pihole:/etc/pihole"
      - "${PIHOLE_VOLUME}/etc/dnsmasq.d:/etc/dnsmasq.d"
    networks:
      priv_lan:
        ipv4_address: ${PIHOLE_IP}
      default:

  cloudflared:
    container_name: cloudflared
    user: root
    restart: always
    image: cloudflare/cloudflared:latest
    command: proxy-dns
    environment:
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
      - "TUNNEL_METRICS=0.0.0.0:${CLOUDFLARED_METRICS_PORT}"
      - "TUNNEL_DNS_ADDRESS=0.0.0.0"
      - "TUNNEL_DNS_PORT=53"
    networks:
      default:
        ipv4_address: ${CLOUDFLARED_IP}

  nginx:
    container_name: nginx
    image: "nginx:stable"
    restart: unless-stopped
    volumes:
      - "${PIHOLE_VOLUME}/nginx.conf:/etc/nginx/nginx.conf:ro"
    logging:
      options:
        max-size: 128m
    networks:
      - default

networks:
  priv_lan:
    external: true
  default:
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
