version: "3.6"

services:
  pihole:
    container_name: pihole
    restart: always
    image: pihole/pihole:latest
    environment:
      - "TZ=${TIMEZONE}"
      - "DNS1=${DNS_IP}#53"
      - "DNS2=no"
    volumes:
      - "${PIHOLE_VOLUME}/etc/pihole:/etc/pihole"
      - "${PIHOLE_VOLUME}/etc/dnsmasq.d:/etc/dnsmasq.d"
    networks:
      priv_lan:
        ipv4_address: ${PIHOLE_IP}

networks:
  priv_lan:
    external: true
