version: "3.7"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    networks:
      priv_lan:
        ipv4_address: ${TRAEFIK_IP}
      traefik_lan:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${TRAEFIK_VOLUME}/dynamic_config:/dynamic_config"
      - "${TRAEFIK_VOLUME}/etc/traefik:/etc/traefik"

networks:
  priv_lan:
    external: true
  traefik_lan:
    external: true
