version: "3"

services:
  # MagicMirror² is an open source modular smart mirror platform.
  # With a growing list of installable modules, the MagicMirror² allows you to convert your hallway or bathroom mirror into your personal assistant.
  # https://github.com/MichMich/MagicMirror
  magicmirror:
    container_name: magicmirror
    image: karsten13/magicmirror:latest
    restart: unless-stopped
    networks:
      - default
      - traefik_lan
    volumes:
      - ${MAGICMIRROR_VOLUME}/config:/opt/magic_mirror/config
      - ${MAGICMIRROR_VOLUME}/modules:/opt/magic_mirror/modules
      - ${MAGICMIRROR_VOLUME}/css:/opt/magic_mirror/css
      - ${PHOTO_VOLUME}/photo:/photo
    environment:
      - PUID=${MAGICMIRROR_PUID}
      - MM_OVERRIDE_CSS="false"
      - MM_OVERRIDE_DEFAULT_MODULES="false"
      - TZ=${TIMEZONE}
    command: 
      - npm
      - run
      - server

networks:
  traefik_lan:
    external: true
