version: "3.8"
services:
  tailscale:
    hostname: ${TS_HOSTNAME}
    image: tailscale/tailscale:stable
    restart: unless-stopped
    networks:
      - ts-net
    volumes:
      - "/dev/net/tun:/dev/net/tun"
      - "${TS_VOLUME}/var/lib:/var/lib"
    environment:
      - TS_STATE_DIR=/var/lib/tailscale

  nginx:
    image: "nginx:stable"
    restart: unless-stopped
    network_mode: "service:tailscale"
    volumes:
      - "${TS_VOLUME}/nginx.conf:/etc/nginx/nginx.conf:ro"
    logging:
      options:
        max-size: 128m

networks:
  ts-net:
    external: true
    name: ${TS_NETWORK}
