version: "3.8"
services:
  tailscale:
    container_name: ${TS_HOSTNAME}
    hostname: ${TS_HOSTNAME}
    image: tailscale/tailscale:stable
    restart: always
    networks:
      priv_lan:
        ipv4_address: ${TS_IP}
      traefik_lan:
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/dev/net/tun:/dev/net/tun"
      - "${TS_VOLUME}/var/lib:/var/lib"
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ROUTES=${TS_ROUTES}

networks:
  priv_lan:
    external: true
  traefik_lan:
    external: true
