version: "3.7"

services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    restart: always
    networks:
      - traefik_lan
      - default
    environment:
      - PUID=${JELLYFIN_PUID}
      - PGID=${JELLYFIN_PGID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${JELLYFIN_VOLUME}/config:/config
      - ${JELLYFIN_VOLUME}/etc/jellyfin:/etc/jellyfin
      - ${JELLYFIN_VOLUME}/config/custom-cont-init.d:/custom-cont-init.d:ro
      - ${MEDIA_VOLUME}:/media
    devices:
      - "/dev/dri:/dev/dri"

networks:
  traefik_lan:
    external: true
