version: "3.7"

services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    restart: always
    ports:
      - "${JELLYFIN_PORT}:8096"
    environment:
      - PUID=${JELLYFIN_PUID}
      - PGID=${JELLYFIN_PGID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${JELLYFIN_VOLUME}/config:/config
      - ${JELLYFIN_VOLUME}/config/custom-cont-init.d:/custom-cont-init.d:ro
      - ${MEDIA_VOLUME}:/media
    devices:
      - "/dev/dri:/dev/dri"

  tailscale:
    hostname: ts-jellyfin
    image: tailscale/tailscale:stable
    volumes:
      - "/dev/net/tun:/dev/net/tun"
      - "${JELLYFIN_VOLUME}/var/lib:/var/lib"
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
