version: "3.8"
services:
  # https://github.com/qdm12/gluetun/
  # Lightweight swiss-knife-like VPN client to multiple VPN service providers
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    ports:
      - "${GLUETUN_PORT}:8388/tcp"
      - "${GLUETUN_PORT}:8388/udp"
    volumes:
      - "${GLUETUN_VOLUME}:/gluetun"
    environment:
      - "VPN_SERVICE_PROVIDER=mullvad"
      - "VPN_TYPE=wireguard"
      - "WIREGUARD_PRIVATE_KEY=${GLUETUN_WIREGUARD_KEY}"
      - "WIREGUARD_ADDRESSES=${GLUETUN_WIREGUARD_ADDRESSES}"
      - "SERVER_CITIES=Singapore"
      - "SHADOWSOCKS=on"
      - "SHADOWSOCKS_LOG=on"
      - "SHADOWSOCKS_PASSWORD=${SHADOWSOCKS_PASSWORD}"
      - "TZ=${TIMEZONE}"
    networks:
      - default
      - traefik_lan

networks:
  traefik_lan:
    external: true
