version: "3.5"

services:
  # PhotoPrism® is an AI-Powered Photos App for the Decentralized Web. 
  # It makes use of the latest technologies to tag and find pictures automatically without getting in your way. 
  # You can run it at home, on a private server, or in the cloud.
  # https://github.com/photoprism/photoprism
  photoprism1:
    container_name: photoprism1
    image: photoprism/photoprism:latest
    depends_on:
      - mariadb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "${PHOTOPRISM1_PORT}:2342" # HTTP port (host:container)
    environment:
      ## INITIAL PASSWORD FOR "admin" USER, MINIMUM 8 CHARACTERS
      PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM1_PASSWORD}"
      PHOTOPRISM_ORIGINALS_LIMIT: -1                 # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_LOG_LEVEL: "error"                  # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_DISABLE_CHOWN: "true"               # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW files
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW files (reduces performance)
      PHOTOPRISM_DETECT_NSFW: "false"                # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "${USER1}"
      PHOTOPRISM_DATABASE_USER: "${MARIADB_USER}"
      PHOTOPRISM_DATABASE_PASSWORD: "${MARIADB_PASSWORD}"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
    ## Start as non-root user before initialization (supported: 0, 33, 50-99, 500-600, and 900-1200):
    user: "${PHOTOPRISM_PUID}:${DOCKER_GUID}"
    ## Share hardware devices with FFmpeg and TensorFlow (optional):
    devices:
     - "/dev/dri:/dev/dri"                         # Intel QSV
    working_dir: "/photoprism" # do not change or remove
    volumes:
      - "${USER_PHOTO_VOLUME}/${USER1}/Photos:/photoprism/originals/${USER1}"
      - "${PHOTOPRISM_VOLUME}/${USER1}/storage:/photoprism/storage"

  photoprism2:
    container_name: photoprism2
    image: photoprism/photoprism:latest
    depends_on:
      - mariadb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "${PHOTOPRISM2_PORT}:2342" # HTTP port (host:container)
    environment:
      ## INITIAL PASSWORD FOR "admin" USER, MINIMUM 8 CHARACTERS
      PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM2_PASSWORD}"
      PHOTOPRISM_ORIGINALS_LIMIT: -1                 # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_LOG_LEVEL: "error"                  # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_DISABLE_CHOWN: "true"               # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW files
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW files (reduces performance)
      PHOTOPRISM_DETECT_NSFW: "false"                # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "${USER2}"
      PHOTOPRISM_DATABASE_USER: "${MARIADB_USER}"
      PHOTOPRISM_DATABASE_PASSWORD: "${MARIADB_PASSWORD}"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
    user: "${PHOTOPRISM_PUID}:${DOCKER_GUID}"
    devices:
     - "/dev/dri:/dev/dri"                         # Intel QSV
    working_dir: "/photoprism" # do not change or remove
    volumes:
      - "${USER_PHOTO_VOLUME}/${USER2}/Photos:/photoprism/originals/${USER2}"
      - "${PHOTOPRISM_VOLUME}/${USER2}/storage:/photoprism/storage"

  photoprism3:
    container_name: photoprism3
    image: photoprism/photoprism:latest
    depends_on:
      - mariadb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "${PHOTOPRISM3_PORT}:2342" # HTTP port (host:container)
    environment:
      ## INITIAL PASSWORD FOR "admin" USER, MINIMUM 8 CHARACTERS
      PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM3_PASSWORD}"
      PHOTOPRISM_ORIGINALS_LIMIT: -1                 # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_LOG_LEVEL: "error"                  # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_DISABLE_CHOWN: "true"               # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW files
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW files (reduces performance)
      PHOTOPRISM_DETECT_NSFW: "false"                # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "${USER3}"
      PHOTOPRISM_DATABASE_USER: "${MARIADB_USER}"
      PHOTOPRISM_DATABASE_PASSWORD: "${MARIADB_PASSWORD}"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
    user: "${PHOTOPRISM_PUID}:${DOCKER_GUID}"
    devices:
     - "/dev/dri:/dev/dri"                         # Intel QSV
    working_dir: "/photoprism" # do not change or remove
    volumes:
      - "${USER_PHOTO_VOLUME}/${USER3}/Photos:/photoprism/originals/${USER3}"
      - "${PHOTOPRISM_VOLUME}/${USER3}/storage:/photoprism/storage"

  photoprism4:
    container_name: photoprism4
    image: photoprism/photoprism:latest
    depends_on:
      - mariadb
    # restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "${PHOTOPRISM4_PORT}:2342" # HTTP port (host:container)
    environment:
      ## INITIAL PASSWORD FOR "admin" USER, MINIMUM 8 CHARACTERS
      PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM4_PASSWORD}"
      PHOTOPRISM_ORIGINALS_LIMIT: -1                 # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_LOG_LEVEL: "error"                  # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_DISABLE_CHOWN: "true"               # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW files
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW files (reduces performance)
      PHOTOPRISM_DETECT_NSFW: "false"                # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "${USER4}"
      PHOTOPRISM_DATABASE_USER: "${MARIADB_USER}"
      PHOTOPRISM_DATABASE_PASSWORD: "${MARIADB_PASSWORD}"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
    user: "${PHOTOPRISM_PUID}:${DOCKER_GUID}"
    devices:
     - "/dev/dri:/dev/dri"                         # Intel QSV
    working_dir: "/photoprism" # do not change or remove
    volumes:
      - "${USER_PHOTO_VOLUME}/${USER4}/Photos:/photoprism/originals/${USER4}"
      - "${PHOTOPRISM_VOLUME}/${USER4}/storage:/photoprism/storage"

  mariadb:
    restart: unless-stopped
    image: mariadb:10.8
    security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "${PHOTOPRISM_VOLUME}/mysql:/var/lib/mysql"
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"

  go-photo-sync:
    container_name: go-photo-sync
    image: "ryosagisu/go-photo-sync:latest"
    user: "${PHOTOPRISM_PUID}:${DOCKER_GUID}"
    depends_on:
      - mariadb
    volumes:
      - "${PHOTOPRISM_VOLUME}/photosync/configs:/configs"
      - "${PHOTO_VOLUME}/photo:/photo"
      - "${USER_PHOTO_VOLUME}/${USER1}/Photos:/originals/${USER1}:ro"
      - "${USER_PHOTO_VOLUME}/${USER2}/Photos:/originals/${USER2}:ro"
      - "${USER_PHOTO_VOLUME}/${USER3}/Photos:/originals/${USER3}:ro"
      - "${USER_PHOTO_VOLUME}/${USER4}/Photos:/originals/${USER4}:ro"
