version: "3.7"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - "PUID=${RADARR_PUID}"
      - "PGID=${DOCKER_PGID}"
      - "TZ=${TIMEZONE}"
      - "TP_HOTIO=true"
      - "TP_THEME=organizr"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${RADARR_VOLUME}/config:/config"
      - "${DATA_VOLUME}:/data"
      - "${RADARR_VOLUME}/etc/cont-init.d/98-themepark-radarr:/etc/cont-init.d/99-themepark"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://1.1.1.1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - "PUID=${SONARR_PUID}"
      - "PGID=${DOCKER_PGID}"
      - "TZ=${TIMEZONE}"
      - "TP_HOTIO=true"
      - "TP_THEME=organizr"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${SONARR_VOLUME}/config:/config"
      - "${DATA_VOLUME}:/data"
      - "${SONARR_VOLUME}/etc/cont-init.d/98-themepark-sonarr:/etc/cont-init.d/99-themepark"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://1.1.1.1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    network_mode: "container:gluetun"
    environment:
      - "PUID=${PROWLARR_PUID}"
      - "PGID=${DOCKER_PGID}"
      - "UMASK=002"
      - "TZ=${TIMEZONE}"
    volumes:
      - "${PROWLARR_VOLUME}/config:/config"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://1.1.1.1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    network_mode: "container:gluetun"
    restart: unless-stopped
    environment:
      - "PUID=${BAZARR_PUID}"
      - "PGID=${DOCKER_PGID}"
      - "TZ=${TIMEZONE}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${BAZARR_VOLUME}/config:/config"
      - "${DATA_VOLUME}/media:/data/media"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://1.1.1.1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:latest
    network_mode: "container:gluetun"
    init: true
    user: ${RECYCLARR_PUID}:${DOCKER_PGID}
    environment:
      - "TZ=${TIMEZONE}"
    volumes:
      - "${RECYCLARR_VOLUME}/config:/config"
